CLASS LHC_ZR_POSTJOURNAL000 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZrPostjournal000
        RESULT result.

      METHODS generateData FOR MODIFY
      IMPORTING keys FOR ACTION ZrPostjournal000~generateData RESULT result.

ENDCLASS.

CLASS LHC_ZR_POSTJOURNAL000 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD generateData.

  ENDMETHOD.
ENDCLASS.
